name: Update S3 bucket

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Update content in th repository and click "Run workflow" to update S3 bucket'
        required: true
        default: 'update'
        type: choice
        options:
          - 'update'

jobs:
  update-S3:
    runs-on: ubuntu-latest

    steps:
      - name: Set initial S3 update status
        run: echo "UPDATE_STATUS=❌ Failed" >> $GITHUB_ENV
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update S3 bucket
        id: update
        run: |
          aws s3 sync . s3://slengpack.click --delete

      - name: Collect status
        id: collect_status_apply
        run: |
          echo "UPDATE_STATUS=$([[ '${{ steps.update.outcome }}' == 'success' ]] && echo '✅ Success')" >> $GITHUB_ENV

      - name: Send Telegram Notification
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            *S3 bucket Update Results*:
            *S3 bucket Update Status*: ${{ env.UPDATE_STATUS }}
